version: '3.9'

services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    tty: true 
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  backend:
    image: jmalloc/echo-server
    ports:
    - "9394:8080"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  silverwind:
    image: lsk569937453/silverwind:0.0.6
    environment:
      CONFIG_FILE_PATH: /data/app/app_config.yaml
      RUST_BACKTRACE: 1
    container_name: silverwind
    restart: unless-stopped
    ports:
      - 6667:6667
      - 8870:8870
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
